const blogData = [
  {
    id: "1",
    category: "cloude sf products",
    image: "/images/c1.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit neque odio corporis sequi, ipsam illum rerum quisquam unde aspernatur placeat voluptas. Nobis cumque incidunt laudantium quia explicabo natus excepturi! Eaque quis placeat aliquam alias, maxime reiciendis fuga. Illo voluptatem earum maxime ullam fugit laborum ab atque laudantium neque sequi reiciendis perspiciatis nesciunt quia cupiditate nemo libero incidunt rem temporibus magnam pariatur, ipsum iste quaerat quos ducimus. Doloribus, aut blanditiis autem tempora nihil quo culpa eos quam delectus asperiores minus, adipisci, temporibus eius? Ipsa earum minus sed culpa, quaerat ea aliquam cumque amet unde. Nostrum non, fuga, cumque iusto voluptatibus architecto tempora eos vel quia recusandae cum, delectus sed molestias nisi aspernatur quo impedit ipsum unde blanditiis obcaecati facere vero! Neque aliquid voluptatum ex, possimus quia ut tenetur, quod officia odio explicabo iure, perspiciatis architecto! Minus cumque eligendi laudantium architecto ratione omnis, alias deleniti quam sapiente hic vel fugiat ab ex nesciunt praesentium assumenda commodi, provident officia rerum quasi! Nisi eveniet quis tempore accusantium ex distinctio, rerum esse doloribus illum! Quidem non itaque expedita qui, molestias ut pariatur reiciendis quam aperiam repellendus sequi, velit deserunt reprehenderit cupiditate voluptatum modi odio necessitatibus. Sit ipsum saepe officia vel accusamus, amet minus sequi consequuntur porro inventore dolorem eligendi cumque laborum veniam. Libero veniam, at eos porro quisquam quis recusandae hic magnam culpa totam dolores harum maxime distinctio officiis quod esse, impedit adipisci? Eius temporibus maiores impedit assumenda eum ducimus expedita, nisi repellat ipsum quidem quos nesciunt laboriosam exercitationem aut adipisci deleniti iste repellendus numquam modi tempora suscipit maxime molestias eos facilis. Ut iusto nulla illum, eligendi repellat nisi odit deserunt voluptates autem fugiat distinctio natus eaque placeat? Culpa inventore amet quibusdam suscipit laudantium alias voluptate quae, nesciunt nam illum quis cupiditate odio. Sint itaque hic sit beatae fugit non saepe et atque nobis! Quisquam.",
    subCategory: "sales",
    title: "sales 1 title",
    author: "Charles Darwin",
    date: "2024-09-09",
  },
  {
    id: "2",
    category: "cloude sf products",
    image: "/images/c2.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit neque odio corporis sequi, ipsam illum rerum quisquam unde aspernatur placeat voluptas. Nobis cumque incidunt laudantium quia explicabo natus excepturi! Eaque quis placeat aliquam alias, maxime reiciendis fuga. Illo voluptatem earum maxime ullam fugit laborum ab atque laudantium neque sequi reiciendis perspiciatis nesciunt quia cupiditate nemo libero incidunt rem temporibus magnam pariatur, ipsum iste quaerat quos ducimus. Doloribus, aut blanditiis autem tempora nihil quo culpa eos quam delectus asperiores minus, adipisci, temporibus eius? Ipsa earum minus sed culpa, quaerat ea aliquam cumque amet unde. Nostrum non, fuga, cumque iusto voluptatibus architecto tempora eos vel quia recusandae cum, delectus sed molestias nisi aspernatur quo impedit ipsum unde blanditiis obcaecati facere vero! Neque aliquid voluptatum ex, possimus quia ut tenetur, quod officia odio explicabo iure, perspiciatis architecto! Minus cumque eligendi laudantium architecto ratione omnis, alias deleniti quam sapiente hic vel fugiat ab ex nesciunt praesentium assumenda commodi, provident officia rerum quasi! Nisi eveniet quis tempore accusantium ex distinctio, rerum esse doloribus illum! Quidem non itaque expedita qui, molestias ut pariatur reiciendis quam aperiam repellendus sequi, velit deserunt reprehenderit cupiditate voluptatum modi odio necessitatibus. Sit ipsum saepe officia vel accusamus, amet minus sequi consequuntur porro inventore dolorem eligendi cumque laborum veniam. Libero veniam, at eos porro quisquam quis recusandae hic magnam culpa totam dolores harum maxime distinctio officiis quod esse, impedit adipisci? Eius temporibus maiores impedit assumenda eum ducimus expedita, nisi repellat ipsum quidem quos nesciunt laboriosam exercitationem aut adipisci deleniti iste repellendus numquam modi tempora suscipit maxime molestias eos facilis. Ut iusto nulla illum, eligendi repellat nisi odit deserunt voluptates autem fugiat distinctio natus eaque placeat? Culpa inventore amet quibusdam suscipit laudantium alias voluptate quae, nesciunt nam illum quis cupiditate odio. Sint itaque hic sit beatae fugit non saepe et atque nobis! Quisquam.",
    subCategory: "sales",
    title: "sales 2 title",
    author: "Charles Darwin",
    date: "2024-09-09",
  },
  {
    id: "3",
    category: "cloude sf products",
    image: "/images/c3.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit neque odio corporis sequi, ipsam illum rerum quisquam unde aspernatur placeat voluptas. Nobis cumque incidunt laudantium quia explicabo natus excepturi! Eaque quis placeat aliquam alias, maxime reiciendis fuga. Illo voluptatem earum maxime ullam fugit laborum ab atque laudantium neque sequi reiciendis perspiciatis nesciunt quia cupiditate nemo libero incidunt rem temporibus magnam pariatur, ipsum iste quaerat quos ducimus. Doloribus, aut blanditiis autem tempora nihil quo culpa eos quam delectus asperiores minus, adipisci, temporibus eius? Ipsa earum minus sed culpa, quaerat ea aliquam cumque amet unde. Nostrum non, fuga, cumque iusto voluptatibus architecto tempora eos vel quia recusandae cum, delectus sed molestias nisi aspernatur quo impedit ipsum unde blanditiis obcaecati facere vero! Neque aliquid voluptatum ex, possimus quia ut tenetur, quod officia odio explicabo iure, perspiciatis architecto! Minus cumque eligendi laudantium architecto ratione omnis, alias deleniti quam sapiente hic vel fugiat ab ex nesciunt praesentium assumenda commodi, provident officia rerum quasi! Nisi eveniet quis tempore accusantium ex distinctio, rerum esse doloribus illum! Quidem non itaque expedita qui, molestias ut pariatur reiciendis quam aperiam repellendus sequi, velit deserunt reprehenderit cupiditate voluptatum modi odio necessitatibus. Sit ipsum saepe officia vel accusamus, amet minus sequi consequuntur porro inventore dolorem eligendi cumque laborum veniam. Libero veniam, at eos porro quisquam quis recusandae hic magnam culpa totam dolores harum maxime distinctio officiis quod esse, impedit adipisci? Eius temporibus maiores impedit assumenda eum ducimus expedita, nisi repellat ipsum quidem quos nesciunt laboriosam exercitationem aut adipisci deleniti iste repellendus numquam modi tempora suscipit maxime molestias eos facilis. Ut iusto nulla illum, eligendi repellat nisi odit deserunt voluptates autem fugiat distinctio natus eaque placeat? Culpa inventore amet quibusdam suscipit laudantium alias voluptate quae, nesciunt nam illum quis cupiditate odio. Sint itaque hic sit beatae fugit non saepe et atque nobis! Quisquam.",
    subCategory: "sales",
    title: "sales 3 title",
    author: "Charles Darwin",
    date: "2024-09-09",
  },
  {
    id: "4",
    category: "cloude sf products",
    image: "/images/c4.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit neque odio corporis sequi, ipsam illum rerum quisquam unde aspernatur placeat voluptas. Nobis cumque incidunt laudantium quia explicabo natus excepturi! Eaque quis placeat aliquam alias, maxime reiciendis fuga. Illo voluptatem earum maxime ullam fugit laborum ab atque laudantium neque sequi reiciendis perspiciatis nesciunt quia cupiditate nemo libero incidunt rem temporibus magnam pariatur, ipsum iste quaerat quos ducimus. Doloribus, aut blanditiis autem tempora nihil quo culpa eos quam delectus asperiores minus, adipisci, temporibus eius? Ipsa earum minus sed culpa, quaerat ea aliquam cumque amet unde. Nostrum non, fuga, cumque iusto voluptatibus architecto tempora eos vel quia recusandae cum, delectus sed molestias nisi aspernatur quo impedit ipsum unde blanditiis obcaecati facere vero! Neque aliquid voluptatum ex, possimus quia ut tenetur, quod officia odio explicabo iure, perspiciatis architecto! Minus cumque eligendi laudantium architecto ratione omnis, alias deleniti quam sapiente hic vel fugiat ab ex nesciunt praesentium assumenda commodi, provident officia rerum quasi! Nisi eveniet quis tempore accusantium ex distinctio, rerum esse doloribus illum! Quidem non itaque expedita qui, molestias ut pariatur reiciendis quam aperiam repellendus sequi, velit deserunt reprehenderit cupiditate voluptatum modi odio necessitatibus. Sit ipsum saepe officia vel accusamus, amet minus sequi consequuntur porro inventore dolorem eligendi cumque laborum veniam. Libero veniam, at eos porro quisquam quis recusandae hic magnam culpa totam dolores harum maxime distinctio officiis quod esse, impedit adipisci? Eius temporibus maiores impedit assumenda eum ducimus expedita, nisi repellat ipsum quidem quos nesciunt laboriosam exercitationem aut adipisci deleniti iste repellendus numquam modi tempora suscipit maxime molestias eos facilis. Ut iusto nulla illum, eligendi repellat nisi odit deserunt voluptates autem fugiat distinctio natus eaque placeat? Culpa inventore amet quibusdam suscipit laudantium alias voluptate quae, nesciunt nam illum quis cupiditate odio. Sint itaque hic sit beatae fugit non saepe et atque nobis! Quisquam.",
    subCategory: "sales",
    title: "sales 4 title",
    author: "Charles Darwin",
    date: "2024-09-09",
  },
  {
    id: "5",
    category: "cloude sf products",
    image: "/images/c5.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit neque odio corporis sequi, ipsam illum rerum quisquam unde aspernatur placeat voluptas. Nobis cumque incidunt laudantium quia explicabo natus excepturi! Eaque quis placeat aliquam alias, maxime reiciendis fuga. Illo voluptatem earum maxime ullam fugit laborum ab atque laudantium neque sequi reiciendis perspiciatis nesciunt quia cupiditate nemo libero incidunt rem temporibus magnam pariatur, ipsum iste quaerat quos ducimus. Doloribus, aut blanditiis autem tempora nihil quo culpa eos quam delectus asperiores minus, adipisci, temporibus eius? Ipsa earum minus sed culpa, quaerat ea aliquam cumque amet unde. Nostrum non, fuga, cumque iusto voluptatibus architecto tempora eos vel quia recusandae cum, delectus sed molestias nisi aspernatur quo impedit ipsum unde blanditiis obcaecati facere vero! Neque aliquid voluptatum ex, possimus quia ut tenetur, quod officia odio explicabo iure, perspiciatis architecto! Minus cumque eligendi laudantium architecto ratione omnis, alias deleniti quam sapiente hic vel fugiat ab ex nesciunt praesentium assumenda commodi, provident officia rerum quasi! Nisi eveniet quis tempore accusantium ex distinctio, rerum esse doloribus illum! Quidem non itaque expedita qui, molestias ut pariatur reiciendis quam aperiam repellendus sequi, velit deserunt reprehenderit cupiditate voluptatum modi odio necessitatibus. Sit ipsum saepe officia vel accusamus, amet minus sequi consequuntur porro inventore dolorem eligendi cumque laborum veniam. Libero veniam, at eos porro quisquam quis recusandae hic magnam culpa totam dolores harum maxime distinctio officiis quod esse, impedit adipisci? Eius temporibus maiores impedit assumenda eum ducimus expedita, nisi repellat ipsum quidem quos nesciunt laboriosam exercitationem aut adipisci deleniti iste repellendus numquam modi tempora suscipit maxime molestias eos facilis. Ut iusto nulla illum, eligendi repellat nisi odit deserunt voluptates autem fugiat distinctio natus eaque placeat? Culpa inventore amet quibusdam suscipit laudantium alias voluptate quae, nesciunt nam illum quis cupiditate odio. Sint itaque hic sit beatae fugit non saepe et atque nobis! Quisquam.",
    subCategory: "services",
    title: "services 1 title",
    author: "Charles Darwin",
    date: "2024-09-09",
  },
  {
    id: "6",
    category: "cloude sf products",
    image: "/images/c1.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit neque odio corporis sequi, ipsam illum rerum quisquam unde aspernatur placeat voluptas. Nobis cumque incidunt laudantium quia explicabo natus excepturi! Eaque quis placeat aliquam alias, maxime reiciendis fuga. Illo voluptatem earum maxime ullam fugit laborum ab atque laudantium neque sequi reiciendis perspiciatis nesciunt quia cupiditate nemo libero incidunt rem temporibus magnam pariatur, ipsum iste quaerat quos ducimus. Doloribus, aut blanditiis autem tempora nihil quo culpa eos quam delectus asperiores minus, adipisci, temporibus eius? Ipsa earum minus sed culpa, quaerat ea aliquam cumque amet unde. Nostrum non, fuga, cumque iusto voluptatibus architecto tempora eos vel quia recusandae cum, delectus sed molestias nisi aspernatur quo impedit ipsum unde blanditiis obcaecati facere vero! Neque aliquid voluptatum ex, possimus quia ut tenetur, quod officia odio explicabo iure, perspiciatis architecto! Minus cumque eligendi laudantium architecto ratione omnis, alias deleniti quam sapiente hic vel fugiat ab ex nesciunt praesentium assumenda commodi, provident officia rerum quasi! Nisi eveniet quis tempore accusantium ex distinctio, rerum esse doloribus illum! Quidem non itaque expedita qui, molestias ut pariatur reiciendis quam aperiam repellendus sequi, velit deserunt reprehenderit cupiditate voluptatum modi odio necessitatibus. Sit ipsum saepe officia vel accusamus, amet minus sequi consequuntur porro inventore dolorem eligendi cumque laborum veniam. Libero veniam, at eos porro quisquam quis recusandae hic magnam culpa totam dolores harum maxime distinctio officiis quod esse, impedit adipisci? Eius temporibus maiores impedit assumenda eum ducimus expedita, nisi repellat ipsum quidem quos nesciunt laboriosam exercitationem aut adipisci deleniti iste repellendus numquam modi tempora suscipit maxime molestias eos facilis. Ut iusto nulla illum, eligendi repellat nisi odit deserunt voluptates autem fugiat distinctio natus eaque placeat? Culpa inventore amet quibusdam suscipit laudantium alias voluptate quae, nesciunt nam illum quis cupiditate odio. Sint itaque hic sit beatae fugit non saepe et atque nobis! Quisquam.",
    subCategory: "services",
    title: "services 2 title",
    author: "Charles Darwin",
    date: "2024-09-09",
  },
  {
    id: "7",
    category: "cloude sf products",
    image: "/images/c2.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit neque odio corporis sequi, ipsam illum rerum quisquam unde aspernatur placeat voluptas. Nobis cumque incidunt laudantium quia explicabo natus excepturi! Eaque quis placeat aliquam alias, maxime reiciendis fuga. Illo voluptatem earum maxime ullam fugit laborum ab atque laudantium neque sequi reiciendis perspiciatis nesciunt quia cupiditate nemo libero incidunt rem temporibus magnam pariatur, ipsum iste quaerat quos ducimus. Doloribus, aut blanditiis autem tempora nihil quo culpa eos quam delectus asperiores minus, adipisci, temporibus eius? Ipsa earum minus sed culpa, quaerat ea aliquam cumque amet unde. Nostrum non, fuga, cumque iusto voluptatibus architecto tempora eos vel quia recusandae cum, delectus sed molestias nisi aspernatur quo impedit ipsum unde blanditiis obcaecati facere vero! Neque aliquid voluptatum ex, possimus quia ut tenetur, quod officia odio explicabo iure, perspiciatis architecto! Minus cumque eligendi laudantium architecto ratione omnis, alias deleniti quam sapiente hic vel fugiat ab ex nesciunt praesentium assumenda commodi, provident officia rerum quasi! Nisi eveniet quis tempore accusantium ex distinctio, rerum esse doloribus illum! Quidem non itaque expedita qui, molestias ut pariatur reiciendis quam aperiam repellendus sequi, velit deserunt reprehenderit cupiditate voluptatum modi odio necessitatibus. Sit ipsum saepe officia vel accusamus, amet minus sequi consequuntur porro inventore dolorem eligendi cumque laborum veniam. Libero veniam, at eos porro quisquam quis recusandae hic magnam culpa totam dolores harum maxime distinctio officiis quod esse, impedit adipisci? Eius temporibus maiores impedit assumenda eum ducimus expedita, nisi repellat ipsum quidem quos nesciunt laboriosam exercitationem aut adipisci deleniti iste repellendus numquam modi tempora suscipit maxime molestias eos facilis. Ut iusto nulla illum, eligendi repellat nisi odit deserunt voluptates autem fugiat distinctio natus eaque placeat? Culpa inventore amet quibusdam suscipit laudantium alias voluptate quae, nesciunt nam illum quis cupiditate odio. Sint itaque hic sit beatae fugit non saepe et atque nobis! Quisquam.",
    subCategory: "services",
    title: "services 3 title",
    author: "Charles Darwin",
    date: "2024-09-09",
  },
  {
    id: "8",
    category: "cloude sf products",
    image: "/images/c4.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit neque odio corporis sequi, ipsam illum rerum quisquam unde aspernatur placeat voluptas. Nobis cumque incidunt laudantium quia explicabo natus excepturi! Eaque quis placeat aliquam alias, maxime reiciendis fuga. Illo voluptatem earum maxime ullam fugit laborum ab atque laudantium neque sequi reiciendis perspiciatis nesciunt quia cupiditate nemo libero incidunt rem temporibus magnam pariatur, ipsum iste quaerat quos ducimus. Doloribus, aut blanditiis autem tempora nihil quo culpa eos quam delectus asperiores minus, adipisci, temporibus eius? Ipsa earum minus sed culpa, quaerat ea aliquam cumque amet unde. Nostrum non, fuga, cumque iusto voluptatibus architecto tempora eos vel quia recusandae cum, delectus sed molestias nisi aspernatur quo impedit ipsum unde blanditiis obcaecati facere vero! Neque aliquid voluptatum ex, possimus quia ut tenetur, quod officia odio explicabo iure, perspiciatis architecto! Minus cumque eligendi laudantium architecto ratione omnis, alias deleniti quam sapiente hic vel fugiat ab ex nesciunt praesentium assumenda commodi, provident officia rerum quasi! Nisi eveniet quis tempore accusantium ex distinctio, rerum esse doloribus illum! Quidem non itaque expedita qui, molestias ut pariatur reiciendis quam aperiam repellendus sequi, velit deserunt reprehenderit cupiditate voluptatum modi odio necessitatibus. Sit ipsum saepe officia vel accusamus, amet minus sequi consequuntur porro inventore dolorem eligendi cumque laborum veniam. Libero veniam, at eos porro quisquam quis recusandae hic magnam culpa totam dolores harum maxime distinctio officiis quod esse, impedit adipisci? Eius temporibus maiores impedit assumenda eum ducimus expedita, nisi repellat ipsum quidem quos nesciunt laboriosam exercitationem aut adipisci deleniti iste repellendus numquam modi tempora suscipit maxime molestias eos facilis. Ut iusto nulla illum, eligendi repellat nisi odit deserunt voluptates autem fugiat distinctio natus eaque placeat? Culpa inventore amet quibusdam suscipit laudantium alias voluptate quae, nesciunt nam illum quis cupiditate odio. Sint itaque hic sit beatae fugit non saepe et atque nobis! Quisquam.",
    subCategory: "filter",
    title: "filter 1 title",
    author: "Charles Darwin",
    date: "2024-09-09",
  },
  {
    id: "9",
    category: "cloude sf products",
    image: "/images/c6.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit neque odio corporis sequi, ipsam illum rerum quisquam unde aspernatur placeat voluptas. Nobis cumque incidunt laudantium quia explicabo natus excepturi! Eaque quis placeat aliquam alias, maxime reiciendis fuga. Illo voluptatem earum maxime ullam fugit laborum ab atque laudantium neque sequi reiciendis perspiciatis nesciunt quia cupiditate nemo libero incidunt rem temporibus magnam pariatur, ipsum iste quaerat quos ducimus. Doloribus, aut blanditiis autem tempora nihil quo culpa eos quam delectus asperiores minus, adipisci, temporibus eius? Ipsa earum minus sed culpa, quaerat ea aliquam cumque amet unde. Nostrum non, fuga, cumque iusto voluptatibus architecto tempora eos vel quia recusandae cum, delectus sed molestias nisi aspernatur quo impedit ipsum unde blanditiis obcaecati facere vero! Neque aliquid voluptatum ex, possimus quia ut tenetur, quod officia odio explicabo iure, perspiciatis architecto! Minus cumque eligendi laudantium architecto ratione omnis, alias deleniti quam sapiente hic vel fugiat ab ex nesciunt praesentium assumenda commodi, provident officia rerum quasi! Nisi eveniet quis tempore accusantium ex distinctio, rerum esse doloribus illum! Quidem non itaque expedita qui, molestias ut pariatur reiciendis quam aperiam repellendus sequi, velit deserunt reprehenderit cupiditate voluptatum modi odio necessitatibus. Sit ipsum saepe officia vel accusamus, amet minus sequi consequuntur porro inventore dolorem eligendi cumque laborum veniam. Libero veniam, at eos porro quisquam quis recusandae hic magnam culpa totam dolores harum maxime distinctio officiis quod esse, impedit adipisci? Eius temporibus maiores impedit assumenda eum ducimus expedita, nisi repellat ipsum quidem quos nesciunt laboriosam exercitationem aut adipisci deleniti iste repellendus numquam modi tempora suscipit maxime molestias eos facilis. Ut iusto nulla illum, eligendi repellat nisi odit deserunt voluptates autem fugiat distinctio natus eaque placeat? Culpa inventore amet quibusdam suscipit laudantium alias voluptate quae, nesciunt nam illum quis cupiditate odio. Sint itaque hic sit beatae fugit non saepe et atque nobis! Quisquam.",
    subCategory: "filter",
    title: "filter 2 title",
    author: "Charles Darwin",
    date: "2024-09-09",
  },
  {
    id: "10",
    category: "cloude sf products",
    image: "/images/c5.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit neque odio corporis sequi, ipsam illum rerum quisquam unde aspernatur placeat voluptas. Nobis cumque incidunt laudantium quia explicabo natus excepturi! Eaque quis placeat aliquam alias, maxime reiciendis fuga. Illo voluptatem earum maxime ullam fugit laborum ab atque laudantium neque sequi reiciendis perspiciatis nesciunt quia cupiditate nemo libero incidunt rem temporibus magnam pariatur, ipsum iste quaerat quos ducimus. Doloribus, aut blanditiis autem tempora nihil quo culpa eos quam delectus asperiores minus, adipisci, temporibus eius? Ipsa earum minus sed culpa, quaerat ea aliquam cumque amet unde. Nostrum non, fuga, cumque iusto voluptatibus architecto tempora eos vel quia recusandae cum, delectus sed molestias nisi aspernatur quo impedit ipsum unde blanditiis obcaecati facere vero! Neque aliquid voluptatum ex, possimus quia ut tenetur, quod officia odio explicabo iure, perspiciatis architecto! Minus cumque eligendi laudantium architecto ratione omnis, alias deleniti quam sapiente hic vel fugiat ab ex nesciunt praesentium assumenda commodi, provident officia rerum quasi! Nisi eveniet quis tempore accusantium ex distinctio, rerum esse doloribus illum! Quidem non itaque expedita qui, molestias ut pariatur reiciendis quam aperiam repellendus sequi, velit deserunt reprehenderit cupiditate voluptatum modi odio necessitatibus. Sit ipsum saepe officia vel accusamus, amet minus sequi consequuntur porro inventore dolorem eligendi cumque laborum veniam. Libero veniam, at eos porro quisquam quis recusandae hic magnam culpa totam dolores harum maxime distinctio officiis quod esse, impedit adipisci? Eius temporibus maiores impedit assumenda eum ducimus expedita, nisi repellat ipsum quidem quos nesciunt laboriosam exercitationem aut adipisci deleniti iste repellendus numquam modi tempora suscipit maxime molestias eos facilis. Ut iusto nulla illum, eligendi repellat nisi odit deserunt voluptates autem fugiat distinctio natus eaque placeat? Culpa inventore amet quibusdam suscipit laudantium alias voluptate quae, nesciunt nam illum quis cupiditate odio. Sint itaque hic sit beatae fugit non saepe et atque nobis! Quisquam.",
    subCategory: "B2B",
    title: "B2B 1 title",
    author: "Charles Darwin",
    date: "2024-09-09",
  },
  {
    id: "11",
    category: "cloude sf products",
    image: "/images/c2.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit neque odio corporis sequi, ipsam illum rerum quisquam unde aspernatur placeat voluptas. Nobis cumque incidunt laudantium quia explicabo natus excepturi! Eaque quis placeat aliquam alias, maxime reiciendis fuga. Illo voluptatem earum maxime ullam fugit laborum ab atque laudantium neque sequi reiciendis perspiciatis nesciunt quia cupiditate nemo libero incidunt rem temporibus magnam pariatur, ipsum iste quaerat quos ducimus. Doloribus, aut blanditiis autem tempora nihil quo culpa eos quam delectus asperiores minus, adipisci, temporibus eius? Ipsa earum minus sed culpa, quaerat ea aliquam cumque amet unde. Nostrum non, fuga, cumque iusto voluptatibus architecto tempora eos vel quia recusandae cum, delectus sed molestias nisi aspernatur quo impedit ipsum unde blanditiis obcaecati facere vero! Neque aliquid voluptatum ex, possimus quia ut tenetur, quod officia odio explicabo iure, perspiciatis architecto! Minus cumque eligendi laudantium architecto ratione omnis, alias deleniti quam sapiente hic vel fugiat ab ex nesciunt praesentium assumenda commodi, provident officia rerum quasi! Nisi eveniet quis tempore accusantium ex distinctio, rerum esse doloribus illum! Quidem non itaque expedita qui, molestias ut pariatur reiciendis quam aperiam repellendus sequi, velit deserunt reprehenderit cupiditate voluptatum modi odio necessitatibus. Sit ipsum saepe officia vel accusamus, amet minus sequi consequuntur porro inventore dolorem eligendi cumque laborum veniam. Libero veniam, at eos porro quisquam quis recusandae hic magnam culpa totam dolores harum maxime distinctio officiis quod esse, impedit adipisci? Eius temporibus maiores impedit assumenda eum ducimus expedita, nisi repellat ipsum quidem quos nesciunt laboriosam exercitationem aut adipisci deleniti iste repellendus numquam modi tempora suscipit maxime molestias eos facilis. Ut iusto nulla illum, eligendi repellat nisi odit deserunt voluptates autem fugiat distinctio natus eaque placeat? Culpa inventore amet quibusdam suscipit laudantium alias voluptate quae, nesciunt nam illum quis cupiditate odio. Sint itaque hic sit beatae fugit non saepe et atque nobis! Quisquam.",
    subCategory: "B2B",
    title: "B2B 2 title",
    author: "Charles Darwin",
    date: "2024-09-09",
  },
  {
    id: "12",
    category: "apex",
    image: "/images/c5.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit neque odio corporis sequi, ipsam illum rerum quisquam unde aspernatur placeat voluptas. Nobis cumque incidunt laudantium quia explicabo natus excepturi! Eaque quis placeat aliquam alias, maxime reiciendis fuga. Illo voluptatem earum maxime ullam fugit laborum ab atque laudantium neque sequi reiciendis perspiciatis nesciunt quia cupiditate nemo libero incidunt rem temporibus magnam pariatur, ipsum iste quaerat quos ducimus. Doloribus, aut blanditiis autem tempora nihil quo culpa eos quam delectus asperiores minus, adipisci, temporibus eius? Ipsa earum minus sed culpa, quaerat ea aliquam cumque amet unde. Nostrum non, fuga, cumque iusto voluptatibus architecto tempora eos vel quia recusandae cum, delectus sed molestias nisi aspernatur quo impedit ipsum unde blanditiis obcaecati facere vero! Neque aliquid voluptatum ex, possimus quia ut tenetur, quod officia odio explicabo iure, perspiciatis architecto! Minus cumque eligendi laudantium architecto ratione omnis, alias deleniti quam sapiente hic vel fugiat ab ex nesciunt praesentium assumenda commodi, provident officia rerum quasi! Nisi eveniet quis tempore accusantium ex distinctio, rerum esse doloribus illum! Quidem non itaque expedita qui, molestias ut pariatur reiciendis quam aperiam repellendus sequi, velit deserunt reprehenderit cupiditate voluptatum modi odio necessitatibus. Sit ipsum saepe officia vel accusamus, amet minus sequi consequuntur porro inventore dolorem eligendi cumque laborum veniam. Libero veniam, at eos porro quisquam quis recusandae hic magnam culpa totam dolores harum maxime distinctio officiis quod esse, impedit adipisci? Eius temporibus maiores impedit assumenda eum ducimus expedita, nisi repellat ipsum quidem quos nesciunt laboriosam exercitationem aut adipisci deleniti iste repellendus numquam modi tempora suscipit maxime molestias eos facilis. Ut iusto nulla illum, eligendi repellat nisi odit deserunt voluptates autem fugiat distinctio natus eaque placeat? Culpa inventore amet quibusdam suscipit laudantium alias voluptate quae, nesciunt nam illum quis cupiditate odio. Sint itaque hic sit beatae fugit non saepe et atque nobis! Quisquam.",
    subCategory: "apex one",
    title: "apex one 1 title",
    author: "Charles Darwin",
    date: "2024-09-09",
  },
  {
    id: "13",
    category: "apex",
    image: "/images/c6.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit neque odio corporis sequi, ipsam illum rerum quisquam unde aspernatur placeat voluptas. Nobis cumque incidunt laudantium quia explicabo natus excepturi! Eaque quis placeat aliquam alias, maxime reiciendis fuga. Illo voluptatem earum maxime ullam fugit laborum ab atque laudantium neque sequi reiciendis perspiciatis nesciunt quia cupiditate nemo libero incidunt rem temporibus magnam pariatur, ipsum iste quaerat quos ducimus. Doloribus, aut blanditiis autem tempora nihil quo culpa eos quam delectus asperiores minus, adipisci, temporibus eius? Ipsa earum minus sed culpa, quaerat ea aliquam cumque amet unde. Nostrum non, fuga, cumque iusto voluptatibus architecto tempora eos vel quia recusandae cum, delectus sed molestias nisi aspernatur quo impedit ipsum unde blanditiis obcaecati facere vero! Neque aliquid voluptatum ex, possimus quia ut tenetur, quod officia odio explicabo iure, perspiciatis architecto! Minus cumque eligendi laudantium architecto ratione omnis, alias deleniti quam sapiente hic vel fugiat ab ex nesciunt praesentium assumenda commodi, provident officia rerum quasi! Nisi eveniet quis tempore accusantium ex distinctio, rerum esse doloribus illum! Quidem non itaque expedita qui, molestias ut pariatur reiciendis quam aperiam repellendus sequi, velit deserunt reprehenderit cupiditate voluptatum modi odio necessitatibus. Sit ipsum saepe officia vel accusamus, amet minus sequi consequuntur porro inventore dolorem eligendi cumque laborum veniam. Libero veniam, at eos porro quisquam quis recusandae hic magnam culpa totam dolores harum maxime distinctio officiis quod esse, impedit adipisci? Eius temporibus maiores impedit assumenda eum ducimus expedita, nisi repellat ipsum quidem quos nesciunt laboriosam exercitationem aut adipisci deleniti iste repellendus numquam modi tempora suscipit maxime molestias eos facilis. Ut iusto nulla illum, eligendi repellat nisi odit deserunt voluptates autem fugiat distinctio natus eaque placeat? Culpa inventore amet quibusdam suscipit laudantium alias voluptate quae, nesciunt nam illum quis cupiditate odio. Sint itaque hic sit beatae fugit non saepe et atque nobis! Quisquam.",
    subCategory: "apex one",
    title: "apex one 2 title",
    author: "Charles Darwin",
    date: "2024-09-09",
  },
  {
    id: "14",
    category: "apex",
    image: "/images/c1.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit neque odio corporis sequi, ipsam illum rerum quisquam unde aspernatur placeat voluptas. Nobis cumque incidunt laudantium quia explicabo natus excepturi! Eaque quis placeat aliquam alias, maxime reiciendis fuga. Illo voluptatem earum maxime ullam fugit laborum ab atque laudantium neque sequi reiciendis perspiciatis nesciunt quia cupiditate nemo libero incidunt rem temporibus magnam pariatur, ipsum iste quaerat quos ducimus. Doloribus, aut blanditiis autem tempora nihil quo culpa eos quam delectus asperiores minus, adipisci, temporibus eius? Ipsa earum minus sed culpa, quaerat ea aliquam cumque amet unde. Nostrum non, fuga, cumque iusto voluptatibus architecto tempora eos vel quia recusandae cum, delectus sed molestias nisi aspernatur quo impedit ipsum unde blanditiis obcaecati facere vero! Neque aliquid voluptatum ex, possimus quia ut tenetur, quod officia odio explicabo iure, perspiciatis architecto! Minus cumque eligendi laudantium architecto ratione omnis, alias deleniti quam sapiente hic vel fugiat ab ex nesciunt praesentium assumenda commodi, provident officia rerum quasi! Nisi eveniet quis tempore accusantium ex distinctio, rerum esse doloribus illum! Quidem non itaque expedita qui, molestias ut pariatur reiciendis quam aperiam repellendus sequi, velit deserunt reprehenderit cupiditate voluptatum modi odio necessitatibus. Sit ipsum saepe officia vel accusamus, amet minus sequi consequuntur porro inventore dolorem eligendi cumque laborum veniam. Libero veniam, at eos porro quisquam quis recusandae hic magnam culpa totam dolores harum maxime distinctio officiis quod esse, impedit adipisci? Eius temporibus maiores impedit assumenda eum ducimus expedita, nisi repellat ipsum quidem quos nesciunt laboriosam exercitationem aut adipisci deleniti iste repellendus numquam modi tempora suscipit maxime molestias eos facilis. Ut iusto nulla illum, eligendi repellat nisi odit deserunt voluptates autem fugiat distinctio natus eaque placeat? Culpa inventore amet quibusdam suscipit laudantium alias voluptate quae, nesciunt nam illum quis cupiditate odio. Sint itaque hic sit beatae fugit non saepe et atque nobis! Quisquam.",
    subCategory: "apex two",
    title: "apex two 1 title",
    author: "Charles Darwin",
    date: "2024-09-09",
  },
  {
    id: "15",
    category: "oracl",
    image: "/images/c3.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit neque odio corporis sequi, ipsam illum rerum quisquam unde aspernatur placeat voluptas. Nobis cumque incidunt laudantium quia explicabo natus excepturi! Eaque quis placeat aliquam alias, maxime reiciendis fuga. Illo voluptatem earum maxime ullam fugit laborum ab atque laudantium neque sequi reiciendis perspiciatis nesciunt quia cupiditate nemo libero incidunt rem temporibus magnam pariatur, ipsum iste quaerat quos ducimus. Doloribus, aut blanditiis autem tempora nihil quo culpa eos quam delectus asperiores minus, adipisci, temporibus eius? Ipsa earum minus sed culpa, quaerat ea aliquam cumque amet unde. Nostrum non, fuga, cumque iusto voluptatibus architecto tempora eos vel quia recusandae cum, delectus sed molestias nisi aspernatur quo impedit ipsum unde blanditiis obcaecati facere vero! Neque aliquid voluptatum ex, possimus quia ut tenetur, quod officia odio explicabo iure, perspiciatis architecto! Minus cumque eligendi laudantium architecto ratione omnis, alias deleniti quam sapiente hic vel fugiat ab ex nesciunt praesentium assumenda commodi, provident officia rerum quasi! Nisi eveniet quis tempore accusantium ex distinctio, rerum esse doloribus illum! Quidem non itaque expedita qui, molestias ut pariatur reiciendis quam aperiam repellendus sequi, velit deserunt reprehenderit cupiditate voluptatum modi odio necessitatibus. Sit ipsum saepe officia vel accusamus, amet minus sequi consequuntur porro inventore dolorem eligendi cumque laborum veniam. Libero veniam, at eos porro quisquam quis recusandae hic magnam culpa totam dolores harum maxime distinctio officiis quod esse, impedit adipisci? Eius temporibus maiores impedit assumenda eum ducimus expedita, nisi repellat ipsum quidem quos nesciunt laboriosam exercitationem aut adipisci deleniti iste repellendus numquam modi tempora suscipit maxime molestias eos facilis. Ut iusto nulla illum, eligendi repellat nisi odit deserunt voluptates autem fugiat distinctio natus eaque placeat? Culpa inventore amet quibusdam suscipit laudantium alias voluptate quae, nesciunt nam illum quis cupiditate odio. Sint itaque hic sit beatae fugit non saepe et atque nobis! Quisquam.",
    title: "oracle 1 title",
    author: "Charles Darwin",
    date: "2024-09-09",
  },
  {
    id: "16",
    category: "oracl",
    image: "/images/c5.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit neque odio corporis sequi, ipsam illum rerum quisquam unde aspernatur placeat voluptas. Nobis cumque incidunt laudantium quia explicabo natus excepturi! Eaque quis placeat aliquam alias, maxime reiciendis fuga. Illo voluptatem earum maxime ullam fugit laborum ab atque laudantium neque sequi reiciendis perspiciatis nesciunt quia cupiditate nemo libero incidunt rem temporibus magnam pariatur, ipsum iste quaerat quos ducimus. Doloribus, aut blanditiis autem tempora nihil quo culpa eos quam delectus asperiores minus, adipisci, temporibus eius? Ipsa earum minus sed culpa, quaerat ea aliquam cumque amet unde. Nostrum non, fuga, cumque iusto voluptatibus architecto tempora eos vel quia recusandae cum, delectus sed molestias nisi aspernatur quo impedit ipsum unde blanditiis obcaecati facere vero! Neque aliquid voluptatum ex, possimus quia ut tenetur, quod officia odio explicabo iure, perspiciatis architecto! Minus cumque eligendi laudantium architecto ratione omnis, alias deleniti quam sapiente hic vel fugiat ab ex nesciunt praesentium assumenda commodi, provident officia rerum quasi! Nisi eveniet quis tempore accusantium ex distinctio, rerum esse doloribus illum! Quidem non itaque expedita qui, molestias ut pariatur reiciendis quam aperiam repellendus sequi, velit deserunt reprehenderit cupiditate voluptatum modi odio necessitatibus. Sit ipsum saepe officia vel accusamus, amet minus sequi consequuntur porro inventore dolorem eligendi cumque laborum veniam. Libero veniam, at eos porro quisquam quis recusandae hic magnam culpa totam dolores harum maxime distinctio officiis quod esse, impedit adipisci? Eius temporibus maiores impedit assumenda eum ducimus expedita, nisi repellat ipsum quidem quos nesciunt laboriosam exercitationem aut adipisci deleniti iste repellendus numquam modi tempora suscipit maxime molestias eos facilis. Ut iusto nulla illum, eligendi repellat nisi odit deserunt voluptates autem fugiat distinctio natus eaque placeat? Culpa inventore amet quibusdam suscipit laudantium alias voluptate quae, nesciunt nam illum quis cupiditate odio. Sint itaque hic sit beatae fugit non saepe et atque nobis! Quisquam.",
    title: "oracle 2 title",
    author: "Charles Darwin",
    date: "2024-09-09",
  },
  {
    id: "17",
    category: "oracl",
    image: "/images/c2.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit neque odio corporis sequi, ipsam illum rerum quisquam unde aspernatur placeat voluptas. Nobis cumque incidunt laudantium quia explicabo natus excepturi! Eaque quis placeat aliquam alias, maxime reiciendis fuga. Illo voluptatem earum maxime ullam fugit laborum ab atque laudantium neque sequi reiciendis perspiciatis nesciunt quia cupiditate nemo libero incidunt rem temporibus magnam pariatur, ipsum iste quaerat quos ducimus. Doloribus, aut blanditiis autem tempora nihil quo culpa eos quam delectus asperiores minus, adipisci, temporibus eius? Ipsa earum minus sed culpa, quaerat ea aliquam cumque amet unde. Nostrum non, fuga, cumque iusto voluptatibus architecto tempora eos vel quia recusandae cum, delectus sed molestias nisi aspernatur quo impedit ipsum unde blanditiis obcaecati facere vero! Neque aliquid voluptatum ex, possimus quia ut tenetur, quod officia odio explicabo iure, perspiciatis architecto! Minus cumque eligendi laudantium architecto ratione omnis, alias deleniti quam sapiente hic vel fugiat ab ex nesciunt praesentium assumenda commodi, provident officia rerum quasi! Nisi eveniet quis tempore accusantium ex distinctio, rerum esse doloribus illum! Quidem non itaque expedita qui, molestias ut pariatur reiciendis quam aperiam repellendus sequi, velit deserunt reprehenderit cupiditate voluptatum modi odio necessitatibus. Sit ipsum saepe officia vel accusamus, amet minus sequi consequuntur porro inventore dolorem eligendi cumque laborum veniam. Libero veniam, at eos porro quisquam quis recusandae hic magnam culpa totam dolores harum maxime distinctio officiis quod esse, impedit adipisci? Eius temporibus maiores impedit assumenda eum ducimus expedita, nisi repellat ipsum quidem quos nesciunt laboriosam exercitationem aut adipisci deleniti iste repellendus numquam modi tempora suscipit maxime molestias eos facilis. Ut iusto nulla illum, eligendi repellat nisi odit deserunt voluptates autem fugiat distinctio natus eaque placeat? Culpa inventore amet quibusdam suscipit laudantium alias voluptate quae, nesciunt nam illum quis cupiditate odio. Sint itaque hic sit beatae fugit non saepe et atque nobis! Quisquam.",
    title: "oracle 3 title",
    author: "Charles Darwin",
    date: "2024-09-09",
  },
  {
    id: "18",
    category: "visual Force",
    image: "/images/c4.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit neque odio corporis sequi, ipsam illum rerum quisquam unde aspernatur placeat voluptas. Nobis cumque incidunt laudantium quia explicabo natus excepturi! Eaque quis placeat aliquam alias, maxime reiciendis fuga. Illo voluptatem earum maxime ullam fugit laborum ab atque laudantium neque sequi reiciendis perspiciatis nesciunt quia cupiditate nemo libero incidunt rem temporibus magnam pariatur, ipsum iste quaerat quos ducimus. Doloribus, aut blanditiis autem tempora nihil quo culpa eos quam delectus asperiores minus, adipisci, temporibus eius? Ipsa earum minus sed culpa, quaerat ea aliquam cumque amet unde. Nostrum non, fuga, cumque iusto voluptatibus architecto tempora eos vel quia recusandae cum, delectus sed molestias nisi aspernatur quo impedit ipsum unde blanditiis obcaecati facere vero! Neque aliquid voluptatum ex, possimus quia ut tenetur, quod officia odio explicabo iure, perspiciatis architecto! Minus cumque eligendi laudantium architecto ratione omnis, alias deleniti quam sapiente hic vel fugiat ab ex nesciunt praesentium assumenda commodi, provident officia rerum quasi! Nisi eveniet quis tempore accusantium ex distinctio, rerum esse doloribus illum! Quidem non itaque expedita qui, molestias ut pariatur reiciendis quam aperiam repellendus sequi, velit deserunt reprehenderit cupiditate voluptatum modi odio necessitatibus. Sit ipsum saepe officia vel accusamus, amet minus sequi consequuntur porro inventore dolorem eligendi cumque laborum veniam. Libero veniam, at eos porro quisquam quis recusandae hic magnam culpa totam dolores harum maxime distinctio officiis quod esse, impedit adipisci? Eius temporibus maiores impedit assumenda eum ducimus expedita, nisi repellat ipsum quidem quos nesciunt laboriosam exercitationem aut adipisci deleniti iste repellendus numquam modi tempora suscipit maxime molestias eos facilis. Ut iusto nulla illum, eligendi repellat nisi odit deserunt voluptates autem fugiat distinctio natus eaque placeat? Culpa inventore amet quibusdam suscipit laudantium alias voluptate quae, nesciunt nam illum quis cupiditate odio. Sint itaque hic sit beatae fugit non saepe et atque nobis! Quisquam.",
    title: "visual Force 1 title",
    author: "Charles Darwin",
    date: "2024-09-09",
  },
  {
    id: "19",
    category: "visual Force",
    image: "/images/c1.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit neque odio corporis sequi, ipsam illum rerum quisquam unde aspernatur placeat voluptas. Nobis cumque incidunt laudantium quia explicabo natus excepturi! Eaque quis placeat aliquam alias, maxime reiciendis fuga. Illo voluptatem earum maxime ullam fugit laborum ab atque laudantium neque sequi reiciendis perspiciatis nesciunt quia cupiditate nemo libero incidunt rem temporibus magnam pariatur, ipsum iste quaerat quos ducimus. Doloribus, aut blanditiis autem tempora nihil quo culpa eos quam delectus asperiores minus, adipisci, temporibus eius? Ipsa earum minus sed culpa, quaerat ea aliquam cumque amet unde. Nostrum non, fuga, cumque iusto voluptatibus architecto tempora eos vel quia recusandae cum, delectus sed molestias nisi aspernatur quo impedit ipsum unde blanditiis obcaecati facere vero! Neque aliquid voluptatum ex, possimus quia ut tenetur, quod officia odio explicabo iure, perspiciatis architecto! Minus cumque eligendi laudantium architecto ratione omnis, alias deleniti quam sapiente hic vel fugiat ab ex nesciunt praesentium assumenda commodi, provident officia rerum quasi! Nisi eveniet quis tempore accusantium ex distinctio, rerum esse doloribus illum! Quidem non itaque expedita qui, molestias ut pariatur reiciendis quam aperiam repellendus sequi, velit deserunt reprehenderit cupiditate voluptatum modi odio necessitatibus. Sit ipsum saepe officia vel accusamus, amet minus sequi consequuntur porro inventore dolorem eligendi cumque laborum veniam. Libero veniam, at eos porro quisquam quis recusandae hic magnam culpa totam dolores harum maxime distinctio officiis quod esse, impedit adipisci? Eius temporibus maiores impedit assumenda eum ducimus expedita, nisi repellat ipsum quidem quos nesciunt laboriosam exercitationem aut adipisci deleniti iste repellendus numquam modi tempora suscipit maxime molestias eos facilis. Ut iusto nulla illum, eligendi repellat nisi odit deserunt voluptates autem fugiat distinctio natus eaque placeat? Culpa inventore amet quibusdam suscipit laudantium alias voluptate quae, nesciunt nam illum quis cupiditate odio. Sint itaque hic sit beatae fugit non saepe et atque nobis! Quisquam.",
    title: "visual Force 2 title",
    author: "Charles Darwin",
    date: "2024-09-09",
  },
  {
    id: "20",
    category: "visual Force",
    image: "/images/c2.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit neque odio corporis sequi, ipsam illum rerum quisquam unde aspernatur placeat voluptas. Nobis cumque incidunt laudantium quia explicabo natus excepturi! Eaque quis placeat aliquam alias, maxime reiciendis fuga. Illo voluptatem earum maxime ullam fugit laborum ab atque laudantium neque sequi reiciendis perspiciatis nesciunt quia cupiditate nemo libero incidunt rem temporibus magnam pariatur, ipsum iste quaerat quos ducimus. Doloribus, aut blanditiis autem tempora nihil quo culpa eos quam delectus asperiores minus, adipisci, temporibus eius? Ipsa earum minus sed culpa, quaerat ea aliquam cumque amet unde. Nostrum non, fuga, cumque iusto voluptatibus architecto tempora eos vel quia recusandae cum, delectus sed molestias nisi aspernatur quo impedit ipsum unde blanditiis obcaecati facere vero! Neque aliquid voluptatum ex, possimus quia ut tenetur, quod officia odio explicabo iure, perspiciatis architecto! Minus cumque eligendi laudantium architecto ratione omnis, alias deleniti quam sapiente hic vel fugiat ab ex nesciunt praesentium assumenda commodi, provident officia rerum quasi! Nisi eveniet quis tempore accusantium ex distinctio, rerum esse doloribus illum! Quidem non itaque expedita qui, molestias ut pariatur reiciendis quam aperiam repellendus sequi, velit deserunt reprehenderit cupiditate voluptatum modi odio necessitatibus. Sit ipsum saepe officia vel accusamus, amet minus sequi consequuntur porro inventore dolorem eligendi cumque laborum veniam. Libero veniam, at eos porro quisquam quis recusandae hic magnam culpa totam dolores harum maxime distinctio officiis quod esse, impedit adipisci? Eius temporibus maiores impedit assumenda eum ducimus expedita, nisi repellat ipsum quidem quos nesciunt laboriosam exercitationem aut adipisci deleniti iste repellendus numquam modi tempora suscipit maxime molestias eos facilis. Ut iusto nulla illum, eligendi repellat nisi odit deserunt voluptates autem fugiat distinctio natus eaque placeat? Culpa inventore amet quibusdam suscipit laudantium alias voluptate quae, nesciunt nam illum quis cupiditate odio. Sint itaque hic sit beatae fugit non saepe et atque nobis! Quisquam.",
    title: "visual Force 3 title",
    author: "Charles Darwin",
    date: "2024-09-09",
  },
  {
    id: "21",
    category: "SFDX",
    image: "/images/c3.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit neque odio corporis sequi, ipsam illum rerum quisquam unde aspernatur placeat voluptas. Nobis cumque incidunt laudantium quia explicabo natus excepturi! Eaque quis placeat aliquam alias, maxime reiciendis fuga. Illo voluptatem earum maxime ullam fugit laborum ab atque laudantium neque sequi reiciendis perspiciatis nesciunt quia cupiditate nemo libero incidunt rem temporibus magnam pariatur, ipsum iste quaerat quos ducimus. Doloribus, aut blanditiis autem tempora nihil quo culpa eos quam delectus asperiores minus, adipisci, temporibus eius? Ipsa earum minus sed culpa, quaerat ea aliquam cumque amet unde. Nostrum non, fuga, cumque iusto voluptatibus architecto tempora eos vel quia recusandae cum, delectus sed molestias nisi aspernatur quo impedit ipsum unde blanditiis obcaecati facere vero! Neque aliquid voluptatum ex, possimus quia ut tenetur, quod officia odio explicabo iure, perspiciatis architecto! Minus cumque eligendi laudantium architecto ratione omnis, alias deleniti quam sapiente hic vel fugiat ab ex nesciunt praesentium assumenda commodi, provident officia rerum quasi! Nisi eveniet quis tempore accusantium ex distinctio, rerum esse doloribus illum! Quidem non itaque expedita qui, molestias ut pariatur reiciendis quam aperiam repellendus sequi, velit deserunt reprehenderit cupiditate voluptatum modi odio necessitatibus. Sit ipsum saepe officia vel accusamus, amet minus sequi consequuntur porro inventore dolorem eligendi cumque laborum veniam. Libero veniam, at eos porro quisquam quis recusandae hic magnam culpa totam dolores harum maxime distinctio officiis quod esse, impedit adipisci? Eius temporibus maiores impedit assumenda eum ducimus expedita, nisi repellat ipsum quidem quos nesciunt laboriosam exercitationem aut adipisci deleniti iste repellendus numquam modi tempora suscipit maxime molestias eos facilis. Ut iusto nulla illum, eligendi repellat nisi odit deserunt voluptates autem fugiat distinctio natus eaque placeat? Culpa inventore amet quibusdam suscipit laudantium alias voluptate quae, nesciunt nam illum quis cupiditate odio. Sint itaque hic sit beatae fugit non saepe et atque nobis! Quisquam.",
    title: "SDFX 1 title",
    author: "Charles Darwin",
    date: "2024-09-09",
  },
  {
    id: "22",
    category: "SFDX",
    image: "/images/c4.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit neque odio corporis sequi, ipsam illum rerum quisquam unde aspernatur placeat voluptas. Nobis cumque incidunt laudantium quia explicabo natus excepturi! Eaque quis placeat aliquam alias, maxime reiciendis fuga. Illo voluptatem earum maxime ullam fugit laborum ab atque laudantium neque sequi reiciendis perspiciatis nesciunt quia cupiditate nemo libero incidunt rem temporibus magnam pariatur, ipsum iste quaerat quos ducimus. Doloribus, aut blanditiis autem tempora nihil quo culpa eos quam delectus asperiores minus, adipisci, temporibus eius? Ipsa earum minus sed culpa, quaerat ea aliquam cumque amet unde. Nostrum non, fuga, cumque iusto voluptatibus architecto tempora eos vel quia recusandae cum, delectus sed molestias nisi aspernatur quo impedit ipsum unde blanditiis obcaecati facere vero! Neque aliquid voluptatum ex, possimus quia ut tenetur, quod officia odio explicabo iure, perspiciatis architecto! Minus cumque eligendi laudantium architecto ratione omnis, alias deleniti quam sapiente hic vel fugiat ab ex nesciunt praesentium assumenda commodi, provident officia rerum quasi! Nisi eveniet quis tempore accusantium ex distinctio, rerum esse doloribus illum! Quidem non itaque expedita qui, molestias ut pariatur reiciendis quam aperiam repellendus sequi, velit deserunt reprehenderit cupiditate voluptatum modi odio necessitatibus. Sit ipsum saepe officia vel accusamus, amet minus sequi consequuntur porro inventore dolorem eligendi cumque laborum veniam. Libero veniam, at eos porro quisquam quis recusandae hic magnam culpa totam dolores harum maxime distinctio officiis quod esse, impedit adipisci? Eius temporibus maiores impedit assumenda eum ducimus expedita, nisi repellat ipsum quidem quos nesciunt laboriosam exercitationem aut adipisci deleniti iste repellendus numquam modi tempora suscipit maxime molestias eos facilis. Ut iusto nulla illum, eligendi repellat nisi odit deserunt voluptates autem fugiat distinctio natus eaque placeat? Culpa inventore amet quibusdam suscipit laudantium alias voluptate quae, nesciunt nam illum quis cupiditate odio. Sint itaque hic sit beatae fugit non saepe et atque nobis! Quisquam.",
    title: "SDFX 2 title",
    author: "Charles Darwin",
    date: "2024-09-09",
  },
  {
    id: "23",
    category: "SFDX",
    image: "/images/c5.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit neque odio corporis sequi, ipsam illum rerum quisquam unde aspernatur placeat voluptas. Nobis cumque incidunt laudantium quia explicabo natus excepturi! Eaque quis placeat aliquam alias, maxime reiciendis fuga. Illo voluptatem earum maxime ullam fugit laborum ab atque laudantium neque sequi reiciendis perspiciatis nesciunt quia cupiditate nemo libero incidunt rem temporibus magnam pariatur, ipsum iste quaerat quos ducimus. Doloribus, aut blanditiis autem tempora nihil quo culpa eos quam delectus asperiores minus, adipisci, temporibus eius? Ipsa earum minus sed culpa, quaerat ea aliquam cumque amet unde. Nostrum non, fuga, cumque iusto voluptatibus architecto tempora eos vel quia recusandae cum, delectus sed molestias nisi aspernatur quo impedit ipsum unde blanditiis obcaecati facere vero! Neque aliquid voluptatum ex, possimus quia ut tenetur, quod officia odio explicabo iure, perspiciatis architecto! Minus cumque eligendi laudantium architecto ratione omnis, alias deleniti quam sapiente hic vel fugiat ab ex nesciunt praesentium assumenda commodi, provident officia rerum quasi! Nisi eveniet quis tempore accusantium ex distinctio, rerum esse doloribus illum! Quidem non itaque expedita qui, molestias ut pariatur reiciendis quam aperiam repellendus sequi, velit deserunt reprehenderit cupiditate voluptatum modi odio necessitatibus. Sit ipsum saepe officia vel accusamus, amet minus sequi consequuntur porro inventore dolorem eligendi cumque laborum veniam. Libero veniam, at eos porro quisquam quis recusandae hic magnam culpa totam dolores harum maxime distinctio officiis quod esse, impedit adipisci? Eius temporibus maiores impedit assumenda eum ducimus expedita, nisi repellat ipsum quidem quos nesciunt laboriosam exercitationem aut adipisci deleniti iste repellendus numquam modi tempora suscipit maxime molestias eos facilis. Ut iusto nulla illum, eligendi repellat nisi odit deserunt voluptates autem fugiat distinctio natus eaque placeat? Culpa inventore amet quibusdam suscipit laudantium alias voluptate quae, nesciunt nam illum quis cupiditate odio. Sint itaque hic sit beatae fugit non saepe et atque nobis! Quisquam.",
    title: "SDFX 3 title",
    author: "Charles Darwin",
    date: "2024-09-09",
  },
  {
    id: "24",
    category: "LWC",
    image: "/images/c6.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit neque odio corporis sequi, ipsam illum rerum quisquam unde aspernatur placeat voluptas. Nobis cumque incidunt laudantium quia explicabo natus excepturi! Eaque quis placeat aliquam alias, maxime reiciendis fuga. Illo voluptatem earum maxime ullam fugit laborum ab atque laudantium neque sequi reiciendis perspiciatis nesciunt quia cupiditate nemo libero incidunt rem temporibus magnam pariatur, ipsum iste quaerat quos ducimus. Doloribus, aut blanditiis autem tempora nihil quo culpa eos quam delectus asperiores minus, adipisci, temporibus eius? Ipsa earum minus sed culpa, quaerat ea aliquam cumque amet unde. Nostrum non, fuga, cumque iusto voluptatibus architecto tempora eos vel quia recusandae cum, delectus sed molestias nisi aspernatur quo impedit ipsum unde blanditiis obcaecati facere vero! Neque aliquid voluptatum ex, possimus quia ut tenetur, quod officia odio explicabo iure, perspiciatis architecto! Minus cumque eligendi laudantium architecto ratione omnis, alias deleniti quam sapiente hic vel fugiat ab ex nesciunt praesentium assumenda commodi, provident officia rerum quasi! Nisi eveniet quis tempore accusantium ex distinctio, rerum esse doloribus illum! Quidem non itaque expedita qui, molestias ut pariatur reiciendis quam aperiam repellendus sequi, velit deserunt reprehenderit cupiditate voluptatum modi odio necessitatibus. Sit ipsum saepe officia vel accusamus, amet minus sequi consequuntur porro inventore dolorem eligendi cumque laborum veniam. Libero veniam, at eos porro quisquam quis recusandae hic magnam culpa totam dolores harum maxime distinctio officiis quod esse, impedit adipisci? Eius temporibus maiores impedit assumenda eum ducimus expedita, nisi repellat ipsum quidem quos nesciunt laboriosam exercitationem aut adipisci deleniti iste repellendus numquam modi tempora suscipit maxime molestias eos facilis. Ut iusto nulla illum, eligendi repellat nisi odit deserunt voluptates autem fugiat distinctio natus eaque placeat? Culpa inventore amet quibusdam suscipit laudantium alias voluptate quae, nesciunt nam illum quis cupiditate odio. Sint itaque hic sit beatae fugit non saepe et atque nobis! Quisquam.",
    title: "LWC 1 title",
    author: "Charles Darwin",
    date: "2024-09-09",
  },
  {
    id: "25",
    category: "LWC",
    image: "/images/c1.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit neque odio corporis sequi, ipsam illum rerum quisquam unde aspernatur placeat voluptas. Nobis cumque incidunt laudantium quia explicabo natus excepturi! Eaque quis placeat aliquam alias, maxime reiciendis fuga. Illo voluptatem earum maxime ullam fugit laborum ab atque laudantium neque sequi reiciendis perspiciatis nesciunt quia cupiditate nemo libero incidunt rem temporibus magnam pariatur, ipsum iste quaerat quos ducimus. Doloribus, aut blanditiis autem tempora nihil quo culpa eos quam delectus asperiores minus, adipisci, temporibus eius? Ipsa earum minus sed culpa, quaerat ea aliquam cumque amet unde. Nostrum non, fuga, cumque iusto voluptatibus architecto tempora eos vel quia recusandae cum, delectus sed molestias nisi aspernatur quo impedit ipsum unde blanditiis obcaecati facere vero! Neque aliquid voluptatum ex, possimus quia ut tenetur, quod officia odio explicabo iure, perspiciatis architecto! Minus cumque eligendi laudantium architecto ratione omnis, alias deleniti quam sapiente hic vel fugiat ab ex nesciunt praesentium assumenda commodi, provident officia rerum quasi! Nisi eveniet quis tempore accusantium ex distinctio, rerum esse doloribus illum! Quidem non itaque expedita qui, molestias ut pariatur reiciendis quam aperiam repellendus sequi, velit deserunt reprehenderit cupiditate voluptatum modi odio necessitatibus. Sit ipsum saepe officia vel accusamus, amet minus sequi consequuntur porro inventore dolorem eligendi cumque laborum veniam. Libero veniam, at eos porro quisquam quis recusandae hic magnam culpa totam dolores harum maxime distinctio officiis quod esse, impedit adipisci? Eius temporibus maiores impedit assumenda eum ducimus expedita, nisi repellat ipsum quidem quos nesciunt laboriosam exercitationem aut adipisci deleniti iste repellendus numquam modi tempora suscipit maxime molestias eos facilis. Ut iusto nulla illum, eligendi repellat nisi odit deserunt voluptates autem fugiat distinctio natus eaque placeat? Culpa inventore amet quibusdam suscipit laudantium alias voluptate quae, nesciunt nam illum quis cupiditate odio. Sint itaque hic sit beatae fugit non saepe et atque nobis! Quisquam.",
    title: "LWC 2 title",
    author: "Charles Darwin",
    date: "2024-09-09",
  },
  {
    id: "26",
    category: "LWC",
    image: "/images/c5.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit neque odio corporis sequi, ipsam illum rerum quisquam unde aspernatur placeat voluptas. Nobis cumque incidunt laudantium quia explicabo natus excepturi! Eaque quis placeat aliquam alias, maxime reiciendis fuga. Illo voluptatem earum maxime ullam fugit laborum ab atque laudantium neque sequi reiciendis perspiciatis nesciunt quia cupiditate nemo libero incidunt rem temporibus magnam pariatur, ipsum iste quaerat quos ducimus. Doloribus, aut blanditiis autem tempora nihil quo culpa eos quam delectus asperiores minus, adipisci, temporibus eius? Ipsa earum minus sed culpa, quaerat ea aliquam cumque amet unde. Nostrum non, fuga, cumque iusto voluptatibus architecto tempora eos vel quia recusandae cum, delectus sed molestias nisi aspernatur quo impedit ipsum unde blanditiis obcaecati facere vero! Neque aliquid voluptatum ex, possimus quia ut tenetur, quod officia odio explicabo iure, perspiciatis architecto! Minus cumque eligendi laudantium architecto ratione omnis, alias deleniti quam sapiente hic vel fugiat ab ex nesciunt praesentium assumenda commodi, provident officia rerum quasi! Nisi eveniet quis tempore accusantium ex distinctio, rerum esse doloribus illum! Quidem non itaque expedita qui, molestias ut pariatur reiciendis quam aperiam repellendus sequi, velit deserunt reprehenderit cupiditate voluptatum modi odio necessitatibus. Sit ipsum saepe officia vel accusamus, amet minus sequi consequuntur porro inventore dolorem eligendi cumque laborum veniam. Libero veniam, at eos porro quisquam quis recusandae hic magnam culpa totam dolores harum maxime distinctio officiis quod esse, impedit adipisci? Eius temporibus maiores impedit assumenda eum ducimus expedita, nisi repellat ipsum quidem quos nesciunt laboriosam exercitationem aut adipisci deleniti iste repellendus numquam modi tempora suscipit maxime molestias eos facilis. Ut iusto nulla illum, eligendi repellat nisi odit deserunt voluptates autem fugiat distinctio natus eaque placeat? Culpa inventore amet quibusdam suscipit laudantium alias voluptate quae, nesciunt nam illum quis cupiditate odio. Sint itaque hic sit beatae fugit non saepe et atque nobis! Quisquam.",
    title: "LWC 3 title",
    author: "Charles Darwin",
    date: "2024-09-09",
  },
  {
    id: "27",
    category: "VS Code",
    image: "/images/c6.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit neque odio corporis sequi, ipsam illum rerum quisquam unde aspernatur placeat voluptas. Nobis cumque incidunt laudantium quia explicabo natus excepturi! Eaque quis placeat aliquam alias, maxime reiciendis fuga. Illo voluptatem earum maxime ullam fugit laborum ab atque laudantium neque sequi reiciendis perspiciatis nesciunt quia cupiditate nemo libero incidunt rem temporibus magnam pariatur, ipsum iste quaerat quos ducimus. Doloribus, aut blanditiis autem tempora nihil quo culpa eos quam delectus asperiores minus, adipisci, temporibus eius? Ipsa earum minus sed culpa, quaerat ea aliquam cumque amet unde. Nostrum non, fuga, cumque iusto voluptatibus architecto tempora eos vel quia recusandae cum, delectus sed molestias nisi aspernatur quo impedit ipsum unde blanditiis obcaecati facere vero! Neque aliquid voluptatum ex, possimus quia ut tenetur, quod officia odio explicabo iure, perspiciatis architecto! Minus cumque eligendi laudantium architecto ratione omnis, alias deleniti quam sapiente hic vel fugiat ab ex nesciunt praesentium assumenda commodi, provident officia rerum quasi! Nisi eveniet quis tempore accusantium ex distinctio, rerum esse doloribus illum! Quidem non itaque expedita qui, molestias ut pariatur reiciendis quam aperiam repellendus sequi, velit deserunt reprehenderit cupiditate voluptatum modi odio necessitatibus. Sit ipsum saepe officia vel accusamus, amet minus sequi consequuntur porro inventore dolorem eligendi cumque laborum veniam. Libero veniam, at eos porro quisquam quis recusandae hic magnam culpa totam dolores harum maxime distinctio officiis quod esse, impedit adipisci? Eius temporibus maiores impedit assumenda eum ducimus expedita, nisi repellat ipsum quidem quos nesciunt laboriosam exercitationem aut adipisci deleniti iste repellendus numquam modi tempora suscipit maxime molestias eos facilis. Ut iusto nulla illum, eligendi repellat nisi odit deserunt voluptates autem fugiat distinctio natus eaque placeat? Culpa inventore amet quibusdam suscipit laudantium alias voluptate quae, nesciunt nam illum quis cupiditate odio. Sint itaque hic sit beatae fugit non saepe et atque nobis! Quisquam.",
    title: "VS Code 1 title",
    author: "Charles Darwin",
    date: "2024-09-09",
  },
  {
    id: "28",
    category: "VS Code",
    image: "/images/c3.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit neque odio corporis sequi, ipsam illum rerum quisquam unde aspernatur placeat voluptas. Nobis cumque incidunt laudantium quia explicabo natus excepturi! Eaque quis placeat aliquam alias, maxime reiciendis fuga. Illo voluptatem earum maxime ullam fugit laborum ab atque laudantium neque sequi reiciendis perspiciatis nesciunt quia cupiditate nemo libero incidunt rem temporibus magnam pariatur, ipsum iste quaerat quos ducimus. Doloribus, aut blanditiis autem tempora nihil quo culpa eos quam delectus asperiores minus, adipisci, temporibus eius? Ipsa earum minus sed culpa, quaerat ea aliquam cumque amet unde. Nostrum non, fuga, cumque iusto voluptatibus architecto tempora eos vel quia recusandae cum, delectus sed molestias nisi aspernatur quo impedit ipsum unde blanditiis obcaecati facere vero! Neque aliquid voluptatum ex, possimus quia ut tenetur, quod officia odio explicabo iure, perspiciatis architecto! Minus cumque eligendi laudantium architecto ratione omnis, alias deleniti quam sapiente hic vel fugiat ab ex nesciunt praesentium assumenda commodi, provident officia rerum quasi! Nisi eveniet quis tempore accusantium ex distinctio, rerum esse doloribus illum! Quidem non itaque expedita qui, molestias ut pariatur reiciendis quam aperiam repellendus sequi, velit deserunt reprehenderit cupiditate voluptatum modi odio necessitatibus. Sit ipsum saepe officia vel accusamus, amet minus sequi consequuntur porro inventore dolorem eligendi cumque laborum veniam. Libero veniam, at eos porro quisquam quis recusandae hic magnam culpa totam dolores harum maxime distinctio officiis quod esse, impedit adipisci? Eius temporibus maiores impedit assumenda eum ducimus expedita, nisi repellat ipsum quidem quos nesciunt laboriosam exercitationem aut adipisci deleniti iste repellendus numquam modi tempora suscipit maxime molestias eos facilis. Ut iusto nulla illum, eligendi repellat nisi odit deserunt voluptates autem fugiat distinctio natus eaque placeat? Culpa inventore amet quibusdam suscipit laudantium alias voluptate quae, nesciunt nam illum quis cupiditate odio. Sint itaque hic sit beatae fugit non saepe et atque nobis! Quisquam.",
    title: "VS Code 2 title",
    author: "Charles Darwin",
    date: "2024-09-09",
  },
  {
    id: "29",
    category: "VS Code",
    image: "/images/c4.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit neque odio corporis sequi, ipsam illum rerum quisquam unde aspernatur placeat voluptas. Nobis cumque incidunt laudantium quia explicabo natus excepturi! Eaque quis placeat aliquam alias, maxime reiciendis fuga. Illo voluptatem earum maxime ullam fugit laborum ab atque laudantium neque sequi reiciendis perspiciatis nesciunt quia cupiditate nemo libero incidunt rem temporibus magnam pariatur, ipsum iste quaerat quos ducimus. Doloribus, aut blanditiis autem tempora nihil quo culpa eos quam delectus asperiores minus, adipisci, temporibus eius? Ipsa earum minus sed culpa, quaerat ea aliquam cumque amet unde. Nostrum non, fuga, cumque iusto voluptatibus architecto tempora eos vel quia recusandae cum, delectus sed molestias nisi aspernatur quo impedit ipsum unde blanditiis obcaecati facere vero! Neque aliquid voluptatum ex, possimus quia ut tenetur, quod officia odio explicabo iure, perspiciatis architecto! Minus cumque eligendi laudantium architecto ratione omnis, alias deleniti quam sapiente hic vel fugiat ab ex nesciunt praesentium assumenda commodi, provident officia rerum quasi! Nisi eveniet quis tempore accusantium ex distinctio, rerum esse doloribus illum! Quidem non itaque expedita qui, molestias ut pariatur reiciendis quam aperiam repellendus sequi, velit deserunt reprehenderit cupiditate voluptatum modi odio necessitatibus. Sit ipsum saepe officia vel accusamus, amet minus sequi consequuntur porro inventore dolorem eligendi cumque laborum veniam. Libero veniam, at eos porro quisquam quis recusandae hic magnam culpa totam dolores harum maxime distinctio officiis quod esse, impedit adipisci? Eius temporibus maiores impedit assumenda eum ducimus expedita, nisi repellat ipsum quidem quos nesciunt laboriosam exercitationem aut adipisci deleniti iste repellendus numquam modi tempora suscipit maxime molestias eos facilis. Ut iusto nulla illum, eligendi repellat nisi odit deserunt voluptates autem fugiat distinctio natus eaque placeat? Culpa inventore amet quibusdam suscipit laudantium alias voluptate quae, nesciunt nam illum quis cupiditate odio. Sint itaque hic sit beatae fugit non saepe et atque nobis! Quisquam.",
    title: "VS Code 3 title",
    author: "Charles Darwin",
    date: "2024-09-09",
  },
  {
    id: "30",
    category: "apex",
    image: "/images/c5.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit neque odio corporis sequi, ipsam illum rerum quisquam unde aspernatur placeat voluptas. Nobis cumque incidunt laudantium quia explicabo natus excepturi! Eaque quis placeat aliquam alias, maxime reiciendis fuga. Illo voluptatem earum maxime ullam fugit laborum ab atque laudantium neque sequi reiciendis perspiciatis nesciunt quia cupiditate nemo libero incidunt rem temporibus magnam pariatur, ipsum iste quaerat quos ducimus. Doloribus, aut blanditiis autem tempora nihil quo culpa eos quam delectus asperiores minus, adipisci, temporibus eius? Ipsa earum minus sed culpa, quaerat ea aliquam cumque amet unde. Nostrum non, fuga, cumque iusto voluptatibus architecto tempora eos vel quia recusandae cum, delectus sed molestias nisi aspernatur quo impedit ipsum unde blanditiis obcaecati facere vero! Neque aliquid voluptatum ex, possimus quia ut tenetur, quod officia odio explicabo iure, perspiciatis architecto! Minus cumque eligendi laudantium architecto ratione omnis, alias deleniti quam sapiente hic vel fugiat ab ex nesciunt praesentium assumenda commodi, provident officia rerum quasi! Nisi eveniet quis tempore accusantium ex distinctio, rerum esse doloribus illum! Quidem non itaque expedita qui, molestias ut pariatur reiciendis quam aperiam repellendus sequi, velit deserunt reprehenderit cupiditate voluptatum modi odio necessitatibus. Sit ipsum saepe officia vel accusamus, amet minus sequi consequuntur porro inventore dolorem eligendi cumque laborum veniam. Libero veniam, at eos porro quisquam quis recusandae hic magnam culpa totam dolores harum maxime distinctio officiis quod esse, impedit adipisci? Eius temporibus maiores impedit assumenda eum ducimus expedita, nisi repellat ipsum quidem quos nesciunt laboriosam exercitationem aut adipisci deleniti iste repellendus numquam modi tempora suscipit maxime molestias eos facilis. Ut iusto nulla illum, eligendi repellat nisi odit deserunt voluptates autem fugiat distinctio natus eaque placeat? Culpa inventore amet quibusdam suscipit laudantium alias voluptate quae, nesciunt nam illum quis cupiditate odio. Sint itaque hic sit beatae fugit non saepe et atque nobis! Quisquam.",
    subCategory: "apex two",
    title: "apex two 2 title",
    author: "Charles Darwin",
    date: "2024-09-09",
  },
  {
    id: "31",
    category: "apex",
    image: "/images/c5.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit neque odio corporis sequi, ipsam illum rerum quisquam unde aspernatur placeat voluptas. Nobis cumque incidunt laudantium quia explicabo natus excepturi! Eaque quis placeat aliquam alias, maxime reiciendis fuga. Illo voluptatem earum maxime ullam fugit laborum ab atque laudantium neque sequi reiciendis perspiciatis nesciunt quia cupiditate nemo libero incidunt rem temporibus magnam pariatur, ipsum iste quaerat quos ducimus. Doloribus, aut blanditiis autem tempora nihil quo culpa eos quam delectus asperiores minus, adipisci, temporibus eius? Ipsa earum minus sed culpa, quaerat ea aliquam cumque amet unde. Nostrum non, fuga, cumque iusto voluptatibus architecto tempora eos vel quia recusandae cum, delectus sed molestias nisi aspernatur quo impedit ipsum unde blanditiis obcaecati facere vero! Neque aliquid voluptatum ex, possimus quia ut tenetur, quod officia odio explicabo iure, perspiciatis architecto! Minus cumque eligendi laudantium architecto ratione omnis, alias deleniti quam sapiente hic vel fugiat ab ex nesciunt praesentium assumenda commodi, provident officia rerum quasi! Nisi eveniet quis tempore accusantium ex distinctio, rerum esse doloribus illum! Quidem non itaque expedita qui, molestias ut pariatur reiciendis quam aperiam repellendus sequi, velit deserunt reprehenderit cupiditate voluptatum modi odio necessitatibus. Sit ipsum saepe officia vel accusamus, amet minus sequi consequuntur porro inventore dolorem eligendi cumque laborum veniam. Libero veniam, at eos porro quisquam quis recusandae hic magnam culpa totam dolores harum maxime distinctio officiis quod esse, impedit adipisci? Eius temporibus maiores impedit assumenda eum ducimus expedita, nisi repellat ipsum quidem quos nesciunt laboriosam exercitationem aut adipisci deleniti iste repellendus numquam modi tempora suscipit maxime molestias eos facilis. Ut iusto nulla illum, eligendi repellat nisi odit deserunt voluptates autem fugiat distinctio natus eaque placeat? Culpa inventore amet quibusdam suscipit laudantium alias voluptate quae, nesciunt nam illum quis cupiditate odio. Sint itaque hic sit beatae fugit non saepe et atque nobis! Quisquam.",
    subCategory: "apex two",
    title: "apex two 3 title",
    author: "Charles Darwin",
    date: "2024-09-09",
  },
  {
    id: "32",
    category: "cloude sf products",
    image: "/images/c1.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit neque odio corporis sequi, ipsam illum rerum quisquam unde aspernatur placeat voluptas. Nobis cumque incidunt laudantium quia explicabo natus excepturi! Eaque quis placeat aliquam alias, maxime reiciendis fuga. Illo voluptatem earum maxime ullam fugit laborum ab atque laudantium neque sequi reiciendis perspiciatis nesciunt quia cupiditate nemo libero incidunt rem temporibus magnam pariatur, ipsum iste quaerat quos ducimus. Doloribus, aut blanditiis autem tempora nihil quo culpa eos quam delectus asperiores minus, adipisci, temporibus eius? Ipsa earum minus sed culpa, quaerat ea aliquam cumque amet unde. Nostrum non, fuga, cumque iusto voluptatibus architecto tempora eos vel quia recusandae cum, delectus sed molestias nisi aspernatur quo impedit ipsum unde blanditiis obcaecati facere vero! Neque aliquid voluptatum ex, possimus quia ut tenetur, quod officia odio explicabo iure, perspiciatis architecto! Minus cumque eligendi laudantium architecto ratione omnis, alias deleniti quam sapiente hic vel fugiat ab ex nesciunt praesentium assumenda commodi, provident officia rerum quasi! Nisi eveniet quis tempore accusantium ex distinctio, rerum esse doloribus illum! Quidem non itaque expedita qui, molestias ut pariatur reiciendis quam aperiam repellendus sequi, velit deserunt reprehenderit cupiditate voluptatum modi odio necessitatibus. Sit ipsum saepe officia vel accusamus, amet minus sequi consequuntur porro inventore dolorem eligendi cumque laborum veniam. Libero veniam, at eos porro quisquam quis recusandae hic magnam culpa totam dolores harum maxime distinctio officiis quod esse, impedit adipisci? Eius temporibus maiores impedit assumenda eum ducimus expedita, nisi repellat ipsum quidem quos nesciunt laboriosam exercitationem aut adipisci deleniti iste repellendus numquam modi tempora suscipit maxime molestias eos facilis. Ut iusto nulla illum, eligendi repellat nisi odit deserunt voluptates autem fugiat distinctio natus eaque placeat? Culpa inventore amet quibusdam suscipit laudantium alias voluptate quae, nesciunt nam illum quis cupiditate odio. Sint itaque hic sit beatae fugit non saepe et atque nobis! Quisquam.",
    subCategory: "sales",
    title: "sales 5 title",
    author: "Charles Darwin",
    date: "2024-09-09",
  },
  {
    id: "33",
    category: "cloude sf products",
    image: "/images/c2.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit neque odio corporis sequi, ipsam illum rerum quisquam unde aspernatur placeat voluptas. Nobis cumque incidunt laudantium quia explicabo natus excepturi! Eaque quis placeat aliquam alias, maxime reiciendis fuga. Illo voluptatem earum maxime ullam fugit laborum ab atque laudantium neque sequi reiciendis perspiciatis nesciunt quia cupiditate nemo libero incidunt rem temporibus magnam pariatur, ipsum iste quaerat quos ducimus. Doloribus, aut blanditiis autem tempora nihil quo culpa eos quam delectus asperiores minus, adipisci, temporibus eius? Ipsa earum minus sed culpa, quaerat ea aliquam cumque amet unde. Nostrum non, fuga, cumque iusto voluptatibus architecto tempora eos vel quia recusandae cum, delectus sed molestias nisi aspernatur quo impedit ipsum unde blanditiis obcaecati facere vero! Neque aliquid voluptatum ex, possimus quia ut tenetur, quod officia odio explicabo iure, perspiciatis architecto! Minus cumque eligendi laudantium architecto ratione omnis, alias deleniti quam sapiente hic vel fugiat ab ex nesciunt praesentium assumenda commodi, provident officia rerum quasi! Nisi eveniet quis tempore accusantium ex distinctio, rerum esse doloribus illum! Quidem non itaque expedita qui, molestias ut pariatur reiciendis quam aperiam repellendus sequi, velit deserunt reprehenderit cupiditate voluptatum modi odio necessitatibus. Sit ipsum saepe officia vel accusamus, amet minus sequi consequuntur porro inventore dolorem eligendi cumque laborum veniam. Libero veniam, at eos porro quisquam quis recusandae hic magnam culpa totam dolores harum maxime distinctio officiis quod esse, impedit adipisci? Eius temporibus maiores impedit assumenda eum ducimus expedita, nisi repellat ipsum quidem quos nesciunt laboriosam exercitationem aut adipisci deleniti iste repellendus numquam modi tempora suscipit maxime molestias eos facilis. Ut iusto nulla illum, eligendi repellat nisi odit deserunt voluptates autem fugiat distinctio natus eaque placeat? Culpa inventore amet quibusdam suscipit laudantium alias voluptate quae, nesciunt nam illum quis cupiditate odio. Sint itaque hic sit beatae fugit non saepe et atque nobis! Quisquam.",
    subCategory: "sales",
    title: "sales 6 title",
    author: "Charles Darwin",
    date: "2024-09-09",
  },
  {
    id: "34",
    category: "cloude sf products",
    image: "/images/c3.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit neque odio corporis sequi, ipsam illum rerum quisquam unde aspernatur placeat voluptas. Nobis cumque incidunt laudantium quia explicabo natus excepturi! Eaque quis placeat aliquam alias, maxime reiciendis fuga. Illo voluptatem earum maxime ullam fugit laborum ab atque laudantium neque sequi reiciendis perspiciatis nesciunt quia cupiditate nemo libero incidunt rem temporibus magnam pariatur, ipsum iste quaerat quos ducimus. Doloribus, aut blanditiis autem tempora nihil quo culpa eos quam delectus asperiores minus, adipisci, temporibus eius? Ipsa earum minus sed culpa, quaerat ea aliquam cumque amet unde. Nostrum non, fuga, cumque iusto voluptatibus architecto tempora eos vel quia recusandae cum, delectus sed molestias nisi aspernatur quo impedit ipsum unde blanditiis obcaecati facere vero! Neque aliquid voluptatum ex, possimus quia ut tenetur, quod officia odio explicabo iure, perspiciatis architecto! Minus cumque eligendi laudantium architecto ratione omnis, alias deleniti quam sapiente hic vel fugiat ab ex nesciunt praesentium assumenda commodi, provident officia rerum quasi! Nisi eveniet quis tempore accusantium ex distinctio, rerum esse doloribus illum! Quidem non itaque expedita qui, molestias ut pariatur reiciendis quam aperiam repellendus sequi, velit deserunt reprehenderit cupiditate voluptatum modi odio necessitatibus. Sit ipsum saepe officia vel accusamus, amet minus sequi consequuntur porro inventore dolorem eligendi cumque laborum veniam. Libero veniam, at eos porro quisquam quis recusandae hic magnam culpa totam dolores harum maxime distinctio officiis quod esse, impedit adipisci? Eius temporibus maiores impedit assumenda eum ducimus expedita, nisi repellat ipsum quidem quos nesciunt laboriosam exercitationem aut adipisci deleniti iste repellendus numquam modi tempora suscipit maxime molestias eos facilis. Ut iusto nulla illum, eligendi repellat nisi odit deserunt voluptates autem fugiat distinctio natus eaque placeat? Culpa inventore amet quibusdam suscipit laudantium alias voluptate quae, nesciunt nam illum quis cupiditate odio. Sint itaque hic sit beatae fugit non saepe et atque nobis! Quisquam.",
    subCategory: "sales",
    title: "sales 7 title",
    author: "Charles Darwin",
    date: "2024-09-09",
  },
];

export async function getAllData() {
  return blogData.length;
}

export async function getData({ page = 1, perPage }) {
  const start = Number(page - 1) * perPage;
  const end = start + perPage;
  return blogData.slice(start, end);
}

export async function getSinglePost(id) {
  return blogData.find((blog) => blog.id === id);
}

export async function getRelatedPost(categorie, id) {
  let data = blogData.filter(
    (blog) => blog.category === categorie && blog.id != id
  );
  return data.slice(0, 3);
}

export async function getSubCategorie(subCategorie, page = 1, perPage) {
  const start = Number(page - 1) * perPage;
  const end = start + perPage;
  const dataSubCategorie = blogData.filter(
    (blog) => blog.subCategory === subCategorie
  );
  let dataLength = dataSubCategorie.length;
  const data = dataSubCategorie.slice(start, end);
  return { dataLength, data };
}

export async function getCategorie(categorie, page = 1, perPage) {
  const start = Number(page - 1) * perPage;
  const end = start + perPage;
  const dataCategorie = blogData.filter((blog) => blog.category === categorie);
  let dataLength = dataCategorie.length;
  const data = dataCategorie.slice(start, end);
  return { dataLength, data };
}
